In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
print("Array:", np_array)

Array: [1 2 3 4 5]


In [2]:
print("Shape:", np_array.shape)

Shape: (5,)


In [3]:
print("Datatype:", np_array.dtype)

Datatype: int32


In [4]:
# 2. Create a 2D array of size 4x4 filled with random numbers
rand_array = np.random.rand(4, 4)

In [5]:
print("\n4x4 Random Array:\n", rand_array)


4x4 Random Array:
 [[0.80568167 0.18280688 0.17379921 0.51171108]
 [0.39312543 0.77403347 0.0753422  0.53358372]
 [0.43604512 0.63387326 0.38223931 0.04681285]
 [0.20407699 0.86114217 0.55724063 0.17917662]]


In [6]:
# 3. Generate a NumPy array of 10 evenly spaced values between 1 and 100
lin_array = np.linspace(1, 100, 10)

In [7]:
print("\nEvenly spaced array:", lin_array)


Evenly spaced array: [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [8]:
# 4. Perform addition, subtraction, and multiplication on two NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [9]:
print("\nAddition:", a + b)


Addition: [5 7 9]


In [10]:
print("\nSubstraction:", a - b)


Substraction: [-3 -3 -3]


In [11]:
print("Multiplication:", a * b)

Multiplication: [ 4 10 18]


In [12]:
# 5. Reshape a 1D NumPy array of 12 elements into a 3x4 matrix
arr1d = np.arange(1, 13)
arr2d = arr1d.reshape(3, 4)

In [13]:
print("\nReshaped 3x4 Array:\n", arr2d)


Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# 6. Calculate mean, median, and standard deviation of a NumPy array
data = np.array([1, 2, 3, 4, 5, 6])

In [15]:
print("\nMean:", data.mean())


Mean: 3.5


In [16]:
print("Median:", np.median(data))

Median: 3.5


In [17]:
print("Standard Deviation:", data.std())

Standard Deviation: 1.707825127659933


In [18]:
# 7. Use slicing to extract a subarray from a larger 2D NumPy array
big_array = np.arange(1, 17).reshape(4, 4)
sub_array = big_array[1:3, 1:4] 

In [19]:
print("\nSubarray:\n", sub_array)


Subarray:
 [[ 6  7  8]
 [10 11 12]]


In [20]:
# 8. Save a NumPy array to a .npy file and reload it
np.save("my_array.npy", arr1d)
loaded_array = np.load("my_array.npy")

In [21]:
print("\nLoaded Array:", loaded_array)


Loaded Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
# 9. Demonstrate element-wise comparison operations in NumPy
x = np.array([1, 2, 3])
y = np.array([2, 2, 1])

In [23]:
print("\nElement-wise comparisons:")


Element-wise comparisons:


In [24]:
print("x > y:", x > y)

x > y: [False False  True]


In [25]:
print("x == y:", x == y)

x == y: [False  True False]


In [26]:
# 10. Create an identity matrix using NumPy and display it
identity = np.eye(4)

In [27]:
print("\nIdentity Matrix:\n", identity)


Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
